#!/bin/bash

# This script is taken from
# https://github.com/bethgelab/docker-deeplearning/blob/master/dockerps
# without any modifications under the following license:

# Copyright 2018 Eberhard Karls University of Tübingen
 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
 
#     http://www.apache.org/licenses/LICENSE-2.0
 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


docker ps | while read -r line ; do
    id=`echo $line | cut -d " " -f1`
    if [ "$id" != "CONTAINER" ]
    then
	if `docker exec $id sh -c '[ -z ${OWNER} ]'`
	then
	    if `docker exec $id sh -c '[ -z ${USER} ]'`
	    then
		info=`docker exec $id sh -c 'printf "%-12s %-3s" "unknown" "$GPU"'`
	    else
		info=`docker exec $id sh -c 'printf "%-12s %-3s" "$USER" "$GPU"'`
	    fi
	else
	    info=`docker exec $id sh -c 'printf "%-12s %-3s" "$OWNER" "$GPU"'`
	fi
        echo "$info   $line"
    else
        echo ""
        echo "USER         GPU   $line"
    fi
done
echo ""