#!/bin/bash 

# uncommend if you encounter errors due to agecker being unmounted
# ls /usr/users/agecker # > /dev/null

# Set primary group name
GROUPNAME=ECKERLAB
# Get according group id
GROUPID=$(cut -d: -f3 < <(getent group $GROUPNAME))

# if GPU environment variable not set
if [ -z "$GPU" ]
then  # start cpu container
    docker run --rm -d -p 8888:8888 --user root -e USER=`whoami` \
-e NB_UID=`id -u` -e NB_USER=`whoami` -e NB_GID=$GROUPID -e NB_GROUP=$GROUPNAME \
-w /home/`whoami`/ -e JUPYTER_ENABLE_LAB=yes -e GRANT_SUDO=yes -e CHOWN_HOME=yes \
-v /usr/users/`whoami`:/home/`whoami`/netwhome \
-v /usr/users/agecker:/home/`whoami`/agecker $@
else  # start gpu container
    docker run --rm -d -p 8888:8888 --user root -e USER=`whoami` --gpus $GPU -e GPU=$GPU \
-e NB_UID=`id -u` -e NB_USER=`whoami` -e NB_GID=$GROUPID -e NB_GROUP=$GROUPNAME \
-w /home/`whoami`/ -e JUPYTER_ENABLE_LAB=yes -e GRANT_SUDO=yes -e CHOWN_HOME=yes \
-v /usr/users/`whoami`:/home/`whoami`/netwhome \
-v /usr/users/agecker:/home/`whoami`/agecker $@
fi


